# periods: list[str] = ['5MIN']
# periods: list[str] = ['5MIN', '15MIN']
# periods: list[str] = ['5MIN', '15MIN', '1HRS']
periods: list[str] = ['1HRS']
# periods: list[str] = ['5MIN', '15MIN', '1HRS', '4HRS', '1DAY']
